### ISSUE TITLE
Problem TrainDB.exe startet in Win10 nicht?

### ISSUE THREAD

**Issue by koebi1** [Jakob-Eichberger/TrainDatabase#5]
habe dotnet-sdk-7.0.203-win-x64 und Setup.msi installiert, das TrainDB auch als Admin gestartet, mehrmals neu installiert, 
auch bei einem anderen Win10 Rechner, es startet einfach nicht. Was mache ich falsch?

**Comment by jaak0b** [comment]
Hi @koebi1 danke für deinen Report! 
Ich hab das Verhalten bei mir auch feststellen können und den Bug mit dem [Release v0.6-alpha](https://github.com/Jakob-Eichberger/TrainDatabase/releases/tag/v0.6-alpha) auch schon behoben. 😊 
Wäre dir dankbar wenn du die neue Verison installieren könntest und mir Rueckmeldung geben könntest, ob der Fix bei dir funktioniert hat!

**Comment by koebi1** [comment]
Hallo Jakob,
habe die neue Version installiert. Das Program startete das erste mal
einwandfrei, habe dann eine .z21 Datei eingespielt. Diese Datei war leider
von einer alten Z21 App.
Sofort kam ein Fehler, dass er die Datei nicht lesen kann, ich beendete das
Programm und wollte es neu starten, es kam ein Fehler, den ich im Anhang
als .jpg angehängt habe.
Seitdem kommt bei jedem Neustart dieser Fehler.
Ich habe das Prog nochmals neu installiert, der Fehler kommt immer noch.
Habe den Pc auch neu gestartet, der Fehler kommt trotzdem.

mfg Jakob Morscher




Jakob ***@***.***> schrieb am Di., 2. Mai 2023, 00:04:

**Comment by jaak0b** [comment]
Jakob danke für die Rueckmeldung, ich schließe das Ticket hiermit mal! Für den Import einer Datbank von der alten z21 gibt es hier ein Issue: https://github.com/Jakob-Eichberger/TrainDatabase/issues/6
