### ISSUE TITLE
Importing a z21 database file causes a sql error on next startup

### ISSUE THREAD

**Issue by jaak0b** [Jakob-Eichberger/TrainDatabase#6]
**Is your feature request related to a problem? Please describe.**
When importing an old z21 database file the application crashes because the database from the old app is different from the database from the new z21 app. 

**Describe the solution you'd like**
Add the ability to import the database file from the old z21 app. 

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by jaak0b** [comment]
@koebi1 Im Moment supporte ich nur den Import von der Datenbank von der neuen z21 App. Wäre es möglich dass du mir dein Datenbankfile von der alten z21 App inkl dem Screenshot hier auf Github hochlädst? (Photo hab ich leider nicht gesehn, dass müsstest du über Github und nicht über Email hochladen :/ ) 


Es sollte für den Fehler auch ein LogFile geben, wäre dir ebenfalls sehr dankbar wenn du mir dieses hochladenk könntest, der Pfad ist wie folgt: 

> %appdata%\TrainDatabase\Log

Um die App wieder verwenden zu können müsstest du warscheinlich die Applikationsdaten löschen, weil beim import irgendwas irreperable kaputt gegangen ist. Den folgenden Pfad am besten direkt in den Explorer (oben in die Leiste) kopieren und den geöffneten Ordner löschen: 

> %appdata%\TrainDatabase

**Comment by koebi1** [comment]
Danke  für die Antwort.
Hier die gewünschten Files, das neue z21 File ist leider viel zu gross. (75Mb)
Habe noch ein altes .z21 File gefunden.
Das mit löschen hat auch funktioniert. Danke
![Error_1](https://user-images.githubusercontent.com/22977418/235655713-c111cc50-60e7-4369-9eb8-90e1041403d2.JPG)
[log20230502.txt](https://github.com/Jakob-Eichberger/TrainDatabase/files/11372675/log20230502.txt)

[k12.zip](https://github.com/Jakob-Eichberger/TrainDatabase/files/11372792/k12.zip)

**Comment by koebi1** [comment]
Habe von der alten Z21 App die Daten in die neue Z21 App eingespielt und alles hat einwandfrei funktioniert.

**Comment by koebi1** [comment]
Leider hatte ich beim Neustart des Programms wieder den SQLite Error 1 wie auf dem Bild, habe dann %appdata%\TrainDatabase
gelöscht und alles funktionierte.
![Error_1](https://user-images.githubusercontent.com/22977418/235676933-bc6b7b7b-c9d0-45e7-9970-0edf567f470e.JPG)

**Comment by jaak0b** [comment]
Ok danke für die Files und die Information. Ich schau mir das am Abend an und gib dir bescheid sobald ich einen vermeindlichen fix für das Verhalten hab! 
Lg

**Comment by jaak0b** [comment]
@koebi1 ich hab gerade eben eine Version 0.7.0 released womit der Fehler behoben wurde. Bitte vor dem Installieren den folgenden Ordner noch einmal final löschen:
> %appdata%\TrainDatabase

Das Importieren vom z21 File von der alten Z21 App sollte jetzt auch funktionieren!

**Comment by koebi1** [comment]
bin am testen der neuen Version 0.7.0 es funktioniert alles bis auf die Eingabe eines alten z21Files. Es kommt folgende Meldung:
![Meldung_1](https://user-images.githubusercontent.com/22977418/235852622-a7ecd873-f83c-4c70-b3c4-384b6db74d58.JPG)
ist aber kein Problem ,kann die alten .z21Files auf die neuen .z21 umwandeln.
was noch toll wäre wenn der Geschwindigkeitregler und die Funktonstasten auf Keyboardtasten gelegt werden könnten.

**Comment by jaak0b** [comment]
Jakob danke für die positive Rückmeldung. Hotkeys sind für die Zukunft angedacht! 
Liebe Grüße und vielen dank fürs debuggen helfen!
